# Chapter 11 drives the chapter 10 lab (bgpbook-ch10): deploy that lab
# first (ch10: make up cluster bgp).
.PHONY: svc l2 bgp migrate anycast break-11a heal-11a

svc:
	./svc.sh

l2:
	./l2.sh

bgp:
	./bgpsvc.sh

migrate:
	./migrate.sh

anycast:
	./anycast.sh

break-11a:
	./break11a.sh

heal-11a:
	./heal11a.sh
