#!/usr/bin/env python3
"""Chapter 18: build the Batfish snapshot (the twin's config view) from the
running fabric. Each device file is the Cumulus-concatenated layout Batfish
parses: a hostname line, the interfaces file (whose own "# This file describes
the network interfaces" line is the marker Batfish keys on), then an "frr
version" marker and the FRR config. The twin is the fabric chapter 17
generated; here its config is read for analysis. Uses subprocess ssh, the
same reliable path drift.py and push.py use."""
import os, subprocess, json, yaml
HERE = os.path.dirname(os.path.abspath(__file__))
LAB = os.environ.get("LAB", "bgpbook-ch17")
PASS = os.environ.get("PASS", "Clab123!")
DEVICES = os.environ.get("DEVICES",
    "leaf01 leaf02 leaf03 leaf04 spine01 spine02").split()
# the twin is built from chapter 17's spec; its generated topology is the
# cabling Batfish needs to resolve the unnumbered eBGP sessions.
TOPO = os.environ.get("TOPO", os.path.join(HERE, "..", "ch17", "topo.clab.yml"))

def ssh(dev, cmd):
    base = ["sshpass", "-p", PASS, "ssh", "-o", "StrictHostKeyChecking=no",
            "-o", "UserKnownHostsFile=/dev/null", "-o", "ConnectTimeout=10",
            f"cumulus@clab-{LAB}-{dev}", cmd]
    return subprocess.run(base, capture_output=True, text=True).stdout

def strip_nvue(s):
    skip = ("# Auto-generated by NVUE", "# Any local modifications", "# md5sum:")
    return "\n".join(l for l in s.splitlines() if not l.startswith(skip))

snap = os.path.join(HERE, os.environ.get("SNAP", "snapshot"), "configs")
os.makedirs(snap, exist_ok=True)
for d in DEVICES:
    intf = strip_nvue(ssh(d, "sudo cat /etc/network/interfaces 2>/dev/null"))
    ports = strip_nvue(ssh(d, "sudo cat /etc/cumulus/ports.conf 2>/dev/null"))
    frr = strip_nvue(ssh(d, "sudo cat /etc/frr/frr.conf 2>/dev/null"))
    # The Cumulus-concatenated layout Batfish expects: hostname, then each of
    # interfaces / ports.conf / frr.conf preceded by its exact marker line.
    # The frr marker is the bare string "frr version"; the frr.conf's own
    # version follows. Without the exact markers the interfaces parser runs on
    # into the FRR section and every BGP line reads as unrecognized.
    content = (f"{d}\n"
               f"# This file describes the network interfaces\n{intf}\n\n"
               f"# ports.conf --\n{ports}\n\n"
               f"frr version\nfrr version 7.5\n{frr}\n")
    open(os.path.join(snap, f"{d}.cfg"), "w").write(content)
    print(f"  wrote {d}.cfg ({len(content.splitlines())} lines, "
          f"bgp={'router bgp' in content}, ifaces={intf.count('iface ')})")

# layer-1 topology, from the generated cabling, so Batfish can resolve the
# unnumbered adjacencies (which swp faces which). Switch-to-switch edges only.
sw = set(DEVICES)
edges = []
for link in yaml.safe_load(open(TOPO))["topology"]["links"]:
    (na, ia), (nb, ib) = (e.split(":") for e in link["endpoints"])
    if na in sw and nb in sw:
        edges.append({"node1": {"hostname": na, "interfaceName": ia},
                      "node2": {"hostname": nb, "interfaceName": ib}})
l1 = os.path.join(HERE, os.environ.get("SNAP", "snapshot"), "layer1_topology.json")
json.dump({"edges": edges}, open(l1, "w"), indent=1)
print(f"  wrote layer1_topology.json ({len(edges)} switch-to-switch edges)")
